CREATE TABLE IF NOT EXISTS `major_holder_stats` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `data_date` date NOT NULL COMMENT '集保資料日期',
  `stock_code` varchar(10) NOT NULL COMMENT '股票代號',
  `total_holder_count` int(11) NOT NULL DEFAULT 0 COMMENT '總股東人數',
  `total_share_count` bigint(20) NOT NULL DEFAULT 0 COMMENT '總集保股數',
  `small_holder_count` int(11) NOT NULL DEFAULT 0 COMMENT '50張以下股東人數',
  `small_holder_share_count` bigint(20) NOT NULL DEFAULT 0 COMMENT '50張以下股數',
  `small_holder_ratio` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '50張以下持股比例',
  `mid_holder_count` int(11) NOT NULL DEFAULT 0 COMMENT '50張以上未滿400張股東人數',
  `mid_holder_share_count` bigint(20) NOT NULL DEFAULT 0 COMMENT '50張以上未滿400張股數',
  `mid_holder_ratio` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '50張以上未滿400張持股比例',
  `large_holder_count` int(11) NOT NULL DEFAULT 0 COMMENT '400張以上大戶人數',
  `large_holder_share_count` bigint(20) NOT NULL DEFAULT 0 COMMENT '400張以上大戶股數',
  `large_holder_ratio` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '400張以上大戶持股比例',
  `thousand_lot_holder_count` int(11) NOT NULL DEFAULT 0 COMMENT '1000張以上大戶人數',
  `thousand_lot_share_count` bigint(20) NOT NULL DEFAULT 0 COMMENT '1000張以上大戶股數',
  `thousand_lot_ratio` decimal(10,4) NOT NULL DEFAULT 0.0000 COMMENT '1000張以上大戶持股比例',
  `avg_large_holder_lots` decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '400張以上平均每戶張數',
  `source` varchar(50) NOT NULL DEFAULT 'TDCC' COMMENT '資料來源',
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_major_holder_stock_date` (`data_date`,`stock_code`),
  KEY `idx_major_holder_stock_code` (`stock_code`),
  KEY `idx_major_holder_data_date` (`data_date`),
  KEY `idx_major_holder_ratio` (`large_holder_ratio`),
  KEY `idx_major_holder_thousand_ratio` (`thousand_lot_ratio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='集保大戶籌碼統計表';
