-- V1.3-3-1 策略回測資料表
-- 用途：保存策略選股在歷史日期產生的訊號，以及後續 1 / 3 / 5 個交易日與目前報酬表現

CREATE TABLE IF NOT EXISTS strategy_backtest_runs (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_name VARCHAR(120) NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  market_type VARCHAR(20) NULL,
  strategy_key VARCHAR(64) NULL,
  limit_per_strategy INT UNSIGNED NOT NULL DEFAULT 30,
  trading_days_count INT UNSIGNED NOT NULL DEFAULT 0,
  signal_count INT UNSIGNED NOT NULL DEFAULT 0,
  success_count INT UNSIGNED NOT NULL DEFAULT 0,
  neutral_count INT UNSIGNED NOT NULL DEFAULT 0,
  fail_count INT UNSIGNED NOT NULL DEFAULT 0,
  pending_count INT UNSIGNED NOT NULL DEFAULT 0,
  avg_return_1d DECIMAL(10,4) NULL,
  avg_return_3d DECIMAL(10,4) NULL,
  avg_return_5d DECIMAL(10,4) NULL,
  win_rate_1d DECIMAL(10,4) NULL,
  win_rate_3d DECIMAL(10,4) NULL,
  win_rate_5d DECIMAL(10,4) NULL,
  params_json JSON NULL,
  summary_json JSON NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'running',
  error_message TEXT NULL,
  started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completed_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_strategy_backtest_runs_date (start_date, end_date),
  KEY idx_strategy_backtest_runs_status (status, started_at),
  KEY idx_strategy_backtest_runs_strategy (strategy_key, market_type, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS strategy_backtest_results (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  run_id INT UNSIGNED NOT NULL,
  strategy_key VARCHAR(64) NOT NULL,
  strategy_name VARCHAR(100) NOT NULL,
  stock_code VARCHAR(20) NOT NULL,
  stock_name VARCHAR(100) NULL,
  market_type VARCHAR(20) NULL,
  industry VARCHAR(100) NULL,
  signal_trade_date DATE NOT NULL,
  source_rank INT UNSIGNED NULL,
  strategy_score DECIMAL(12,4) NULL,
  trigger_summary VARCHAR(500) NULL,
  entry_price DECIMAL(12,4) NULL,
  entry_price_date DATE NULL,
  price_after_1d DECIMAL(12,4) NULL,
  price_after_1d_date DATE NULL,
  return_1d_percent DECIMAL(10,4) NULL,
  price_after_3d DECIMAL(12,4) NULL,
  price_after_3d_date DATE NULL,
  return_3d_percent DECIMAL(10,4) NULL,
  price_after_5d DECIMAL(12,4) NULL,
  price_after_5d_date DATE NULL,
  return_5d_percent DECIMAL(10,4) NULL,
  latest_price DECIMAL(12,4) NULL,
  latest_price_date DATE NULL,
  latest_return_percent DECIMAL(10,4) NULL,
  outcome_label VARCHAR(20) NOT NULL DEFAULT 'pending',
  outcome_description VARCHAR(255) NULL,
  is_success TINYINT(1) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_strategy_backtest_result (run_id, strategy_key, stock_code, signal_trade_date),
  KEY idx_strategy_backtest_results_run (run_id, strategy_key, outcome_label),
  KEY idx_strategy_backtest_results_stock (stock_code, signal_trade_date),
  KEY idx_strategy_backtest_results_return_5d (return_5d_percent),
  KEY idx_strategy_backtest_results_latest_return (latest_return_percent),
  CONSTRAINT fk_strategy_backtest_results_run_id
    FOREIGN KEY (run_id) REFERENCES strategy_backtest_runs(id)
    ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
