-- Stock Radar V1.5 市場風險引擎資料表
-- 建議先在 MariaDB 執行：npm run market-risk:setup

CREATE TABLE IF NOT EXISTS `market_risk_snapshots` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trade_date` date NOT NULL COMMENT '資料交易日期',
  `snapshot_time` datetime NOT NULL DEFAULT current_timestamp() COMMENT '快照建立時間',
  `product_code` varchar(20) NOT NULL DEFAULT 'TX' COMMENT '期貨商品代號，例如 TX',
  `product_name` varchar(120) DEFAULT NULL COMMENT '期貨商品名稱',
  `contract_month` varchar(20) NOT NULL DEFAULT '' COMMENT '到期月份週別',
  `session_type` varchar(30) NOT NULL DEFAULT 'after_hours' COMMENT 'regular / after_hours / unknown',
  `open_price` decimal(12,2) DEFAULT NULL COMMENT '開盤價',
  `high_price` decimal(12,2) DEFAULT NULL COMMENT '最高價',
  `low_price` decimal(12,2) DEFAULT NULL COMMENT '最低價',
  `last_price` decimal(12,2) DEFAULT NULL COMMENT '最後成交價',
  `change_point` decimal(12,2) DEFAULT NULL COMMENT '漲跌點數',
  `change_percent` decimal(8,4) DEFAULT NULL COMMENT '漲跌百分比',
  `total_volume` bigint(20) DEFAULT NULL COMMENT '合計成交量',
  `regular_volume` bigint(20) DEFAULT NULL COMMENT '一般交易時段成交量',
  `after_hours_volume` bigint(20) DEFAULT NULL COMMENT '盤後交易時段成交量',
  `reference_index_point` decimal(12,2) DEFAULT NULL COMMENT '台股收盤指數參考值',
  `market_risk_score` int(11) NOT NULL DEFAULT 70 COMMENT '市場風險分數 0-100，越高代表風險越低',
  `market_risk_level` varchar(20) NOT NULL DEFAULT '正常' COMMENT '積極 / 正常 / 保守 / 高風險',
  `market_mode` varchar(20) NOT NULL DEFAULT 'RANGE' COMMENT 'BULL / RANGE / BEAR',
  `night_signal` varchar(50) DEFAULT NULL COMMENT '夜盤訊號',
  `risk_summary` varchar(500) DEFAULT NULL COMMENT '市場風險摘要',
  `source` varchar(100) NOT NULL DEFAULT 'TAIFEX OpenAPI DailyMarket',
  `source_url` varchar(500) DEFAULT NULL,
  `raw_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`raw_json`)),
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_market_risk_snapshot` (`trade_date`,`product_code`,`contract_month`,`session_type`),
  KEY `idx_market_risk_snapshots_date` (`trade_date`),
  KEY `idx_market_risk_snapshots_score` (`market_risk_score`),
  KEY `idx_market_risk_snapshots_mode` (`market_mode`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V1.5 市場風險快照表';

CREATE TABLE IF NOT EXISTS `market_risk_adjusted_scores` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `trade_date` date NOT NULL COMMENT '分析日期',
  `stock_code` varchar(10) NOT NULL COMMENT '股票代號',
  `source_snapshot_id` bigint(20) unsigned DEFAULT NULL COMMENT '來源市場風險快照 ID',
  `close_score` int(11) NOT NULL DEFAULT 0 COMMENT '原本收盤籌碼分數',
  `market_risk_score` int(11) NOT NULL DEFAULT 70 COMMENT '市場風險分數',
  `market_risk_level` varchar(20) NOT NULL DEFAULT '正常',
  `market_mode` varchar(20) NOT NULL DEFAULT 'RANGE',
  `risk_weight` decimal(6,4) NOT NULL DEFAULT 0.9500 COMMENT '市場風險降權係數',
  `night_adjustment` int(11) NOT NULL DEFAULT 0 COMMENT '夜盤修正分數',
  `adjusted_score` int(11) NOT NULL DEFAULT 0 COMMENT '夜盤修正後分數',
  `risk_summary` varchar(500) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_market_risk_adjusted_stock` (`trade_date`,`stock_code`),
  KEY `idx_market_risk_adjusted_date_score` (`trade_date`,`adjusted_score`),
  KEY `idx_market_risk_adjusted_stock` (`stock_code`),
  KEY `idx_market_risk_adjusted_snapshot` (`source_snapshot_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V1.5 市場風險修正後個股分數';
