CREATE TABLE IF NOT EXISTS `technical_breakout_signals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_date` DATE NOT NULL,
  `stock_code` VARCHAR(20) NOT NULL,
  `stock_name` VARCHAR(100) NULL,
  `market_type` VARCHAR(20) NULL,
  `industry` VARCHAR(100) NULL,
  `breakout_score` DECIMAL(6,2) NOT NULL DEFAULT 0,
  `breakout_level` VARCHAR(20) NOT NULL DEFAULT 'NEUTRAL',
  `breakout_type` VARCHAR(60) NOT NULL DEFAULT '技術觀察',
  `breakout_tags` TEXT NULL,
  `close_price` DECIMAL(12,2) NULL,
  `price_change` DECIMAL(12,2) NULL,
  `price_change_percent` DECIMAL(8,4) NULL,
  `volume` BIGINT NULL,
  `volume_ratio_5` DECIMAL(10,4) NULL,
  `ma5` DECIMAL(12,4) NULL,
  `ma20` DECIMAL(12,4) NULL,
  `ma60` DECIMAL(12,4) NULL,
  `high_20` DECIMAL(12,4) NULL,
  `high_60` DECIMAL(12,4) NULL,
  `is_20d_high` TINYINT(1) NOT NULL DEFAULT 0,
  `is_60d_high` TINYINT(1) NOT NULL DEFAULT 0,
  `is_ma_bullish` TINYINT(1) NOT NULL DEFAULT 0,
  `is_volume_breakout` TINYINT(1) NOT NULL DEFAULT 0,
  `is_box_breakout` TINYINT(1) NOT NULL DEFAULT 0,
  `overheat_risk` VARCHAR(20) NOT NULL DEFAULT 'LOW',
  `support_risk` VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
  `chip_score` DECIMAL(6,2) NULL,
  `global_adjusted_score` DECIMAL(6,2) NULL,
  `market_adjusted_score` DECIMAL(6,2) NULL,
  `reason_summary` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_breakout_trade_stock` (`trade_date`, `stock_code`),
  KEY `idx_breakout_trade_score` (`trade_date`, `breakout_score`),
  KEY `idx_breakout_level` (`breakout_level`),
  KEY `idx_breakout_market` (`market_type`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `technical_breakout_summaries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_date` DATE NOT NULL,
  `market_type` VARCHAR(20) NOT NULL DEFAULT '全部',
  `total_count` INT NOT NULL DEFAULT 0,
  `strong_count` INT NOT NULL DEFAULT 0,
  `watch_count` INT NOT NULL DEFAULT 0,
  `early_count` INT NOT NULL DEFAULT 0,
  `avg_breakout_score` DECIMAL(8,2) NULL,
  `top_breakout_score` DECIMAL(8,2) NULL,
  `top_stock_code` VARCHAR(20) NULL,
  `top_stock_name` VARCHAR(100) NULL,
  `generated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_breakout_summary_trade_market` (`trade_date`, `market_type`),
  KEY `idx_breakout_summary_trade` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
