CREATE TABLE IF NOT EXISTS `main_force_signals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_date` DATE NOT NULL COMMENT '訊號分析日期，預設取最新 daily_prices 交易日',
  `source_data_date` DATE NULL COMMENT '使用的集保大戶資料日期',
  `stock_code` VARCHAR(20) NOT NULL,
  `stock_name` VARCHAR(100) NULL,
  `market_type` VARCHAR(20) NULL,
  `industry` VARCHAR(100) NULL,
  `main_force_score` DECIMAL(6,2) NOT NULL DEFAULT 0 COMMENT '主力籌碼分數 0-100',
  `main_force_level` VARCHAR(20) NOT NULL DEFAULT 'NEUTRAL' COMMENT 'STRONG / WATCH / EARLY / NEUTRAL / RISK',
  `main_force_status` VARCHAR(60) NOT NULL DEFAULT '主力觀察',
  `main_force_trend` VARCHAR(20) NOT NULL DEFAULT 'NEUTRAL' COMMENT 'ACCUMULATING / LOCKING / NEUTRAL / DISTRIBUTING',
  `estimated_main_force_cost` DECIMAL(12,2) NULL COMMENT '估算主力成本，依近20日量價加權近似',
  `close_price` DECIMAL(12,2) NULL,
  `cost_gap_percent` DECIMAL(8,4) NULL COMMENT '現價相對估算成本差距%',
  `large_holder_ratio` DECIMAL(10,4) NULL,
  `large_holder_ratio_change` DECIMAL(10,4) NULL,
  `thousand_lot_ratio` DECIMAL(10,4) NULL,
  `thousand_lot_ratio_change` DECIMAL(10,4) NULL,
  `large_holder_count` INT NULL,
  `large_holder_count_change` INT NULL,
  `small_holder_count` INT NULL,
  `small_holder_count_change` INT NULL,
  `foreign_net_buy` BIGINT NULL,
  `investment_trust_net_buy` BIGINT NULL,
  `dealer_net_buy` BIGINT NULL,
  `volume_ratio_5` DECIMAL(10,4) NULL,
  `breakout_score` DECIMAL(6,2) NULL,
  `chip_score` DECIMAL(6,2) NULL,
  `accumulation_signal` VARCHAR(30) NOT NULL DEFAULT 'NEUTRAL',
  `lock_chip_signal` VARCHAR(30) NOT NULL DEFAULT 'NEUTRAL',
  `distribution_risk` VARCHAR(30) NOT NULL DEFAULT 'LOW',
  `reason_summary` VARCHAR(500) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_main_force_trade_stock` (`trade_date`, `stock_code`),
  KEY `idx_main_force_trade_score` (`trade_date`, `main_force_score`),
  KEY `idx_main_force_level` (`main_force_level`),
  KEY `idx_main_force_market` (`market_type`, `trade_date`),
  KEY `idx_main_force_trend` (`main_force_trend`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V1.8 主力籌碼引擎訊號';

CREATE TABLE IF NOT EXISTS `main_force_summaries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_date` DATE NOT NULL,
  `market_type` VARCHAR(20) NOT NULL DEFAULT '全部',
  `total_count` INT NOT NULL DEFAULT 0,
  `strong_count` INT NOT NULL DEFAULT 0,
  `watch_count` INT NOT NULL DEFAULT 0,
  `early_count` INT NOT NULL DEFAULT 0,
  `risk_count` INT NOT NULL DEFAULT 0,
  `avg_main_force_score` DECIMAL(8,2) NULL,
  `top_main_force_score` DECIMAL(8,2) NULL,
  `top_stock_code` VARCHAR(20) NULL,
  `top_stock_name` VARCHAR(100) NULL,
  `generated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_main_force_summary_trade_market` (`trade_date`, `market_type`),
  KEY `idx_main_force_summary_trade` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V1.8 主力籌碼引擎摘要';
