CREATE TABLE IF NOT EXISTS `big_holder_trend_signals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_date` DATE NOT NULL COMMENT '訊號分析日期，預設取最新 chip_scores 交易日',
  `source_data_date` DATE NULL COMMENT '使用的 TDCC 集保資料日期',
  `stock_code` VARCHAR(20) NOT NULL,
  `stock_name` VARCHAR(100) NULL,
  `market_type` VARCHAR(20) NULL,
  `industry` VARCHAR(100) NULL,
  `big_holder_trend_score` DECIMAL(6,2) NOT NULL DEFAULT 0 COMMENT '大戶趨勢分數 0-100',
  `big_holder_level` VARCHAR(20) NOT NULL DEFAULT 'NEUTRAL' COMMENT 'STRONG / WATCH / EARLY / NEUTRAL / RISK',
  `big_holder_status` VARCHAR(80) NOT NULL DEFAULT '大戶趨勢觀察',
  `concentration_trend` VARCHAR(20) NOT NULL DEFAULT 'NEUTRAL' COMMENT 'UP / DOWN / NEUTRAL',
  `concentration_signal` VARCHAR(30) NOT NULL DEFAULT 'NEUTRAL' COMMENT 'ACCUMULATING / LOCKING / NEUTRAL / LOOSENING',
  `large_holder_ratio` DECIMAL(10,4) NULL COMMENT '400張以上大戶持股比例',
  `large_holder_ratio_4w_change` DECIMAL(10,4) NULL COMMENT '400張以上大戶比例近4週變化',
  `large_holder_ratio_8w_change` DECIMAL(10,4) NULL COMMENT '400張以上大戶比例近8週變化',
  `thousand_lot_ratio` DECIMAL(10,4) NULL COMMENT '1000張以上大戶持股比例',
  `thousand_lot_ratio_4w_change` DECIMAL(10,4) NULL COMMENT '1000張以上大戶比例近4週變化',
  `thousand_lot_ratio_8w_change` DECIMAL(10,4) NULL COMMENT '1000張以上大戶比例近8週變化',
  `large_holder_count` INT NULL COMMENT '400張以上大戶人數',
  `large_holder_count_4w_change` INT NULL COMMENT '400張以上大戶人數近4週變化',
  `large_holder_count_8w_change` INT NULL COMMENT '400張以上大戶人數近8週變化',
  `small_holder_count` INT NULL COMMENT '50張以下散戶人數',
  `small_holder_count_4w_change` INT NULL COMMENT '50張以下散戶人數近4週變化',
  `small_holder_count_8w_change` INT NULL COMMENT '50張以下散戶人數近8週變化',
  `retail_pressure` VARCHAR(30) NOT NULL DEFAULT 'NEUTRAL' COMMENT '散戶籌碼壓力 LOW / MEDIUM / HIGH / NEUTRAL',
  `distribution_risk` VARCHAR(30) NOT NULL DEFAULT 'LOW' COMMENT '出貨風險 LOW / MEDIUM / HIGH',
  `divergence_signal` VARCHAR(60) NULL COMMENT '大戶/股價背離狀態',
  `close_price` DECIMAL(12,2) NULL,
  `price_change_4w_percent` DECIMAL(10,4) NULL,
  `price_change_8w_percent` DECIMAL(10,4) NULL,
  `chip_score` DECIMAL(6,2) NULL,
  `main_force_score` DECIMAL(6,2) NULL,
  `reason_summary` VARCHAR(600) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_big_holder_trend_trade_stock` (`trade_date`, `stock_code`),
  KEY `idx_big_holder_trend_trade_score` (`trade_date`, `big_holder_trend_score`),
  KEY `idx_big_holder_trend_level` (`big_holder_level`),
  KEY `idx_big_holder_trend_market` (`market_type`, `trade_date`),
  KEY `idx_big_holder_trend_concentration` (`concentration_trend`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V1.9 大戶持股趨勢訊號';

CREATE TABLE IF NOT EXISTS `big_holder_trend_summaries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_date` DATE NOT NULL,
  `source_data_date` DATE NULL,
  `market_type` VARCHAR(20) NOT NULL DEFAULT '全部',
  `total_count` INT NOT NULL DEFAULT 0,
  `strong_count` INT NOT NULL DEFAULT 0,
  `watch_count` INT NOT NULL DEFAULT 0,
  `early_count` INT NOT NULL DEFAULT 0,
  `risk_count` INT NOT NULL DEFAULT 0,
  `accumulating_count` INT NOT NULL DEFAULT 0,
  `loosen_count` INT NOT NULL DEFAULT 0,
  `avg_big_holder_trend_score` DECIMAL(8,2) NULL,
  `top_big_holder_trend_score` DECIMAL(8,2) NULL,
  `top_stock_code` VARCHAR(20) NULL,
  `top_stock_name` VARCHAR(100) NULL,
  `generated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_big_holder_summary_trade_market` (`trade_date`, `market_type`),
  KEY `idx_big_holder_summary_trade` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V1.9 大戶持股趨勢摘要';
