CREATE TABLE IF NOT EXISTS `ai_selection_signals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_date` DATE NOT NULL COMMENT 'AI 多因子分析日期，預設取最新 chip_scores 交易日',
  `stock_code` VARCHAR(20) NOT NULL,
  `stock_name` VARCHAR(100) NULL,
  `market_type` VARCHAR(20) NULL,
  `industry` VARCHAR(100) NULL,
  `ai_strength_score` DECIMAL(6,2) NOT NULL DEFAULT 0 COMMENT 'AI 強勢分數 0-100',
  `ai_level` VARCHAR(20) NOT NULL DEFAULT 'NEUTRAL' COMMENT 'AI_STRONG / AI_WATCH / AI_OBSERVE / NEUTRAL / AI_RISK',
  `ai_status` VARCHAR(80) NOT NULL DEFAULT 'AI 觀察',
  `candidate_horizon` VARCHAR(20) NOT NULL DEFAULT '1-5D' COMMENT '1D / 1-3D / 1-5D / AVOID',
  `close_score` DECIMAL(6,2) NULL,
  `night_adjusted_score` DECIMAL(6,2) NULL,
  `global_adjusted_score` DECIMAL(6,2) NULL,
  `chip_factor_score` DECIMAL(6,2) NULL,
  `technical_factor_score` DECIMAL(6,2) NULL,
  `main_force_factor_score` DECIMAL(6,2) NULL,
  `big_holder_factor_score` DECIMAL(6,2) NULL,
  `market_factor_score` DECIMAL(6,2) NULL,
  `global_factor_score` DECIMAL(6,2) NULL,
  `fundamental_factor_score` DECIMAL(6,2) NULL,
  `breakout_score` DECIMAL(6,2) NULL,
  `main_force_score` DECIMAL(6,2) NULL,
  `big_holder_trend_score` DECIMAL(6,2) NULL,
  `market_risk_score` DECIMAL(6,2) NULL,
  `global_risk_score` DECIMAL(6,2) NULL,
  `opening_gap_probability` DECIMAL(6,2) NULL,
  `eps` DECIMAL(12,4) NULL,
  `revenue_yoy_percent` DECIMAL(12,4) NULL,
  `risk_level` VARCHAR(20) NOT NULL DEFAULT 'MEDIUM' COMMENT 'LOW / MEDIUM / HIGH',
  `risk_flags` VARCHAR(500) NULL,
  `recommend_reason` VARCHAR(700) NULL,
  `avoid_reason` VARCHAR(700) NULL,
  `factor_json` LONGTEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_selection_trade_stock` (`trade_date`, `stock_code`),
  KEY `idx_ai_selection_trade_score` (`trade_date`, `ai_strength_score`),
  KEY `idx_ai_selection_level` (`ai_level`),
  KEY `idx_ai_selection_market` (`market_type`, `trade_date`),
  KEY `idx_ai_selection_risk` (`risk_level`, `trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V2.0 AI 多因子選股訊號';

CREATE TABLE IF NOT EXISTS `ai_selection_summaries` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `trade_date` DATE NOT NULL,
  `market_type` VARCHAR(20) NOT NULL DEFAULT '全部',
  `total_count` INT NOT NULL DEFAULT 0,
  `strong_count` INT NOT NULL DEFAULT 0,
  `watch_count` INT NOT NULL DEFAULT 0,
  `observe_count` INT NOT NULL DEFAULT 0,
  `risk_count` INT NOT NULL DEFAULT 0,
  `low_risk_count` INT NOT NULL DEFAULT 0,
  `avg_ai_strength_score` DECIMAL(8,2) NULL,
  `top_ai_strength_score` DECIMAL(8,2) NULL,
  `top_stock_code` VARCHAR(20) NULL,
  `top_stock_name` VARCHAR(100) NULL,
  `generated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_selection_summary_trade_market` (`trade_date`, `market_type`),
  KEY `idx_ai_selection_summary_trade` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V2.0 AI 多因子選股摘要';
