CREATE TABLE IF NOT EXISTS `ai_recommendation_feedbacks` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `signal_id` BIGINT UNSIGNED NULL COMMENT '來源 ai_selection_signals.id',
  `signal_trade_date` DATE NOT NULL COMMENT 'AI 推薦日期',
  `stock_code` VARCHAR(20) NOT NULL,
  `stock_name` VARCHAR(100) NULL,
  `market_type` VARCHAR(20) NULL,
  `industry` VARCHAR(100) NULL,
  `ai_strength_score` DECIMAL(6,2) NULL,
  `ai_level` VARCHAR(20) NULL,
  `candidate_horizon` VARCHAR(20) NULL,
  `risk_level` VARCHAR(20) NULL,
  `market_environment` VARCHAR(30) NOT NULL DEFAULT 'UNKNOWN' COMMENT 'BULL / RANGE / BEAR / HIGH_RISK / UNKNOWN',
  `entry_close_price` DECIMAL(12,4) NULL,
  `return_1d_pct` DECIMAL(10,4) NULL,
  `return_3d_pct` DECIMAL(10,4) NULL,
  `return_5d_pct` DECIMAL(10,4) NULL,
  `return_10d_pct` DECIMAL(10,4) NULL,
  `max_return_pct` DECIMAL(10,4) NULL,
  `min_return_pct` DECIMAL(10,4) NULL,
  `feedback_result` VARCHAR(20) NOT NULL DEFAULT 'WAITING' COMMENT 'SUCCESS / PARTIAL / FAIL / WAITING',
  `recommendation_quality_score` DECIMAL(6,2) NOT NULL DEFAULT 50,
  `chip_factor_score` DECIMAL(6,2) NULL,
  `technical_factor_score` DECIMAL(6,2) NULL,
  `main_force_factor_score` DECIMAL(6,2) NULL,
  `big_holder_factor_score` DECIMAL(6,2) NULL,
  `market_factor_score` DECIMAL(6,2) NULL,
  `global_factor_score` DECIMAL(6,2) NULL,
  `fundamental_factor_score` DECIMAL(6,2) NULL,
  `learning_note` VARCHAR(700) NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_feedback_signal` (`signal_trade_date`, `stock_code`),
  KEY `idx_ai_feedback_result` (`feedback_result`, `signal_trade_date`),
  KEY `idx_ai_feedback_level` (`ai_level`, `signal_trade_date`),
  KEY `idx_ai_feedback_environment` (`market_environment`, `signal_trade_date`),
  KEY `idx_ai_feedback_quality` (`recommendation_quality_score`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V2.3 AI 推薦結果回饋紀錄';

CREATE TABLE IF NOT EXISTS `ai_factor_performance_snapshots` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `snapshot_date` DATE NOT NULL,
  `factor_key` VARCHAR(40) NOT NULL COMMENT 'chip / technical / main_force / big_holder / market / global / fundamental',
  `factor_name` VARCHAR(80) NOT NULL,
  `market_environment` VARCHAR(30) NOT NULL DEFAULT 'ALL',
  `sample_count` INT NOT NULL DEFAULT 0,
  `success_count` INT NOT NULL DEFAULT 0,
  `partial_count` INT NOT NULL DEFAULT 0,
  `fail_count` INT NOT NULL DEFAULT 0,
  `waiting_count` INT NOT NULL DEFAULT 0,
  `success_rate_pct` DECIMAL(10,4) NOT NULL DEFAULT 0,
  `avg_return_1d_pct` DECIMAL(10,4) NULL,
  `avg_return_3d_pct` DECIMAL(10,4) NULL,
  `avg_return_5d_pct` DECIMAL(10,4) NULL,
  `avg_return_10d_pct` DECIMAL(10,4) NULL,
  `avg_factor_score` DECIMAL(10,4) NULL,
  `performance_score` DECIMAL(6,2) NOT NULL DEFAULT 50,
  `learning_status` VARCHAR(20) NOT NULL DEFAULT 'OBSERVE' COMMENT 'GOOD / OBSERVE / WEAK / INSUFFICIENT',
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_factor_perf` (`snapshot_date`, `factor_key`, `market_environment`),
  KEY `idx_ai_factor_perf_factor` (`factor_key`, `snapshot_date`),
  KEY `idx_ai_factor_perf_status` (`learning_status`, `snapshot_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V2.3 AI 因子績效快照';

CREATE TABLE IF NOT EXISTS `ai_factor_weight_suggestions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `suggestion_date` DATE NOT NULL,
  `factor_key` VARCHAR(40) NOT NULL,
  `factor_name` VARCHAR(80) NOT NULL,
  `current_weight` DECIMAL(8,4) NOT NULL DEFAULT 0,
  `suggested_weight` DECIMAL(8,4) NOT NULL DEFAULT 0,
  `suggestion_action` VARCHAR(20) NOT NULL DEFAULT 'KEEP' COMMENT 'INCREASE / DECREASE / KEEP',
  `confidence_level` VARCHAR(20) NOT NULL DEFAULT 'LOW' COMMENT 'HIGH / MEDIUM / LOW',
  `sample_count` INT NOT NULL DEFAULT 0,
  `success_rate_pct` DECIMAL(10,4) NOT NULL DEFAULT 0,
  `avg_return_5d_pct` DECIMAL(10,4) NULL,
  `reason` VARCHAR(700) NULL,
  `is_applied` TINYINT(1) NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_ai_weight_suggestion` (`suggestion_date`, `factor_key`),
  KEY `idx_ai_weight_action` (`suggestion_action`, `suggestion_date`),
  KEY `idx_ai_weight_confidence` (`confidence_level`, `suggestion_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='V2.3 AI 因子權重調整建議';
